name: helloworld
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.0.1
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  firebase_analytics: ^10.1.6
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  youtube_player_flutter: ^8.0.0
  path_provider: ^2.0.13
  flutter_map: ^2.2.0
  latlong2: ^0.8.2
  firebase_auth: ^4.3.0
  image_picker_web: ^3.0.0
  camera_web: ^0.3.1
  sqflite: ^2.0.3
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/alarm-clock.png
    - assets/images/clock.png
    - assets/images/coding.png
    - assets/images/development.png
    - assets/images/lady_looking_at_computer.png
    - assets/images/python.png
    - assets/images/thinking.png
    - assets/images/u.png
    - assets/images/ui_ux_design.png
    - assets/images/ui-design.png
    - assets/images/ux_research.png
    - assets/images/video-tutorials.png
    - assets/images/web-development.png
    - assets/images/web.png
    - assets/images/website.png
    - assets/images/bg_1.png
    - assets/images/bg_2.png
    - assets/images/icon_1.png
    - assets/images/icon_2.png
    - assets/images/icon_3.png
    - assets/images/fp.png
    - assets/images/ds.png
    - assets/images/uim.png
    - assets/images/bca.png
    - assets/images/ovo.png
    - assets/images/bri.png
    - assets/images/gopay.png
    
    
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
